#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.9
# In conjunction with Tcl version 8.6
#    Apr 23, 2017 02:43:10 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import ui_support

import main

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = AutoUploadOnDrive (root)
    ui_support.init(root, top)
    root.mainloop()

w = None
def create_AutoUploadOnDrive(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = AutoUploadOnDrive (w)
    ui_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_AutoUploadOnDrive():
    global w
    w.destroy()
    w = None


class AutoUploadOnDrive:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("600x450+449+134")
        top.title("AutoUploadOnDrive")
        top.configure(background="#d9d9d9")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.03, rely=0.02, relheight=0.17, relwidth=0.94)
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=565)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.35, rely=0.27, height=21, width=122)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Auto Upload On Drive''')


        self.Frame2 = Frame(top)
        self.Frame2.place(relx=0.03, rely=0.27, relheight=0.52, relwidth=0.94)
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief=GROOVE)
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(width=565)

        
        # self.scrollbarx = Scrollbar(self.Frame2)
        # self.scrollbarx.pack( fill=BOTH )
        self.scrollbar = Scrollbar(self.Frame2)

        self.mylist = Listbox(self.Frame2, yscrollcommand = self.scrollbar.set  )
        self.mylist.insert(END, "log File:" )

        self.mylist.pack( fill = BOTH )
        self.mylist.place(relx=0.03, rely=0.06, relheight=0.81, relwidth=0.93)
        self.mylist.configure(background="white")
        self.mylist.configure(foreground="black")

        self.scrollbar = Scrollbar(self.mylist)
        self.scrollbar.pack( fill=BOTH )
        self.scrollbar.place(relx=0.97,relheight=0.99, relwidth=0.03)
        self.scrollbar.config( command = self.mylist.yview )
        # self.scrollbarx.config( command = self.mylist.xview )

        self.Button1 = Button(top,command = self.UploadFileButton)
        self.Button1.place(relx=0.05, rely=0.84, height=24, width=77)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Upload File''')
        self.Button1.configure(width=77)

        self.Button2 = Button(top,command = self.UploadFolderButton)
        self.Button2.place(relx=0.22, rely=0.84, height=24, width=87)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Upload Folder''')
        self.Button2.configure(width=87)

        self.Button3 = Button(top,command = self.AutoChangeUploadButton)
        self.Button3.place(relx=0.57, rely=0.84, height=24, width=155)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Auto Change upload folder''')

    def UploadFolderButton(self):
        main.uploadFolderInit(self)

    def UploadFileButton(self):
        main.uploadFileInit(self)

    
    def AutoChangeUploadButton(self):
        main.uploadFileInit(self)

    def pr(self,st):
        try:
            self.mylist.insert(END, st)
        except:
            self.mylist.insert(END, "Error in string")





if __name__ == '__main__':
    vp_start_gui()



